language: python
sudo: false
python:
    - "3.5"
    - "3.6"

matrix:
    include:
        - python: "3.7"
          dist: xenial
          sudo: true

install:
    # tox-travis automatically splits the jobs
    - pip install tox-travis

script:
    - tox
