language: python
sudo: false
stage: "Test"
python:
    - "3.5"
    - "3.6"

matrix:
    include:
        - stage: "Test"
          python: "3.7"
          dist: xenial
          sudo: true

        - stage: "Check"
          name: "ESLint"
          language: node_js
          node_js: "7"
          before_script:
              - npm install eslint
          script:
              - npx eslint ./**/*.js

install:
    # tox-travis automatically splits the jobs
    - pip install tox-travis

script:
    - tox
